// voidspace-ui/src/components/layout/Sidebar.tsx
"use client";

import {
  Home,
  Search,
  User,
  Settings,
  Plus
} from "lucide-react";
import SidebarItem from "./SidebarItem";
import Link from "next/link";
import UserMiniProfile from "./UserMiniProfile";

import { useUIStore } from "@/store/useUIStore";

const navItems = [
  { href: "/", icon: Home, label: "Home" },
  { href: "/explore", icon: Search, label: "Explore" },
  { href: "/profile", icon: User, label: "Profile" },
  { href: "/settings", icon: Settings, label: "Settings" },
];

export default function Sidebar() {
  const { openNewPostModal } = useUIStore();

  return (
    <aside className="hidden md:flex flex-col w-[260px] h-screen fixed left-0 top-0 border-r border-foreground/10 bg-background z-40">
      {/* Logo */}
      <div className="p-8">
        <Link href="/" className="group">
          <h1 className="font-space-grotesk text-2xl font-bold tracking-[-1px] text-foreground transition-all group-hover:tracking-[1px]">
            VOIDSPACE
          </h1>
        </Link>
      </div>

      {/* Navigation */}
      <nav className="flex-1 mt-4">
        {navItems.map((item) => (
          <SidebarItem
            key={item.href}
            href={item.href}
            icon={item.icon}
            label={item.label}
          />
        ))}
      </nav>

      {/* Post Button */}
      <div className="p-6 mt-auto">
        <button 
          onClick={openNewPostModal}
          className="w-full bg-foreground text-background h-[52px] rounded-sm font-bold text-[13px] tracking-[2px] uppercase flex items-center justify-center gap-2 hover:opacity-90 transition-all active:scale-[0.98]"
        >
          <Plus size={18} />
          <span>New Post</span>
        </button>
      </div>

      <UserMiniProfile />
    </aside>
  );
}

// voidspace-ui/app/components/nav/sidebar.vue
<script setup lang="ts">
import logoDark from '~/assets/images/logo_dark.png'
import logoLight from '~/assets/images/logo_light.png'

defineProps<{
    menuItems: {
        label: string
        href: string
        icon?: any
        badge?: number
    }[],
    activePath?: string
}>()


</script>

<template>
    <nav class="hidden lg:flex  flex-col gap-2">
        <!-- Logo -->
        <div class="flex mb-6">
            <img :src="logoDark" alt="VoidSpace Logo" class="h-6 w-auto dark:block hidden" />
            <img :src="logoLight" alt="VoidSpace Logo" class="h-6 w-auto dark:hidden block" />
        </div>

        <!-- Menu Items -->
        <template v-for="item in menuItems" :key="item.label">
            <NuxtLink :to="item.href" active-class="bg-neutral-200 dark:bg-neutral-800 font-bold"
                class="flex items-center gap-3 px-4 py-3 rounded-lg transition-colors hover:bg-neutral-100 dark:hover:bg-neutral-800">
                <component :is="item.icon" class="w-6 h-6" />
                <span class="text-base">{{ item.label }}</span>

                <span v-if="item.badge"
                    class="ml-auto px-2 py-1 rounded-full text-xs bg-neutral-400 dark:bg-neutral-700">
                    {{ item.badge }}
                </span>
            </NuxtLink>
        </template>
    </nav>
</template>
